services:
  backend:
    build:
      context: ./
      dockerfile: containers/backend.dockerfile
    env_file:
      - ./config/backend.env
    volumes:
      - ./backend:/build/backend:rw
      - ./out:/app:rw
      - target-backend:/build/backend/target:rw
      - registry-backend:/usr/local/cargo/registry:rw
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 127.0.0.1:8000:8000
  database:
    image: postgres:16.2-bookworm
    restart: always
    env_file:
      - ./config/database.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cashierdb
    volumes:
      - database:/var/lib/postgresql/data:rw
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d cashierdb -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  target-backend:
  registry-backend:
  database: